name: Testes de API - Petstore

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instalar Newman
        run: npm install -g newman

      - name: Executar testes da Petstore
        run: newman run api-tests/Petstore-QA.postman_collection.json --reporters cli